export const projects = [
    {
        id: '1',
        title: 'MiniGames Hub',
        description: '🎮 A collection of fun mini-games built with React and Tailwind CSS, including Tic Tac Toe, Higher or Lower, and Typing Test. 💡 Showcasing reusable React components, smooth state management, and responsive UI design for an engaging gaming experience. ✨ Built to entertain and inspire!',
        thumbnail: '/assets/thumbnails/minigames-hub.png',
        videoUrl: 'https://www.youtube.com/embed/Z77BVIE4dF8',
        views: '1.5K',
        likes: 172,
        date: '3 months ago',
        githubUrl: 'https://github.com/Shadosxnover/MiniGames-Hub',
    },
    {
        id: '2',
        title: 'Mind Box Game',
        description: '🎮🧠 Box Mind Game: A fun and challenging memory game built with React! Players test their skills by memorizing and repeating sequences of highlighted boxes, with difficulty increasing over time. 💡 Features dynamic sequence generation, smooth transitions, and responsive design for an engaging experience across all devices. ✨',
        thumbnail: '/assets/thumbnails/mind-box-game.png',
        videoUrl: 'https://www.youtube.com/embed/qDN-l7Gvdh4',
        views: '2.3K',
        likes: 214,
        date: '2 months ago',
        githubUrl: 'https://shadosxnover.github.io/Box-Mind-Game/',
    },
    {
        id: '3',
        title: '3D Dice Roller',
        description: '🎲✨ 3D Dice Roller Game built with React and Three.js! A fun journey exploring 3D modeling, smooth animations, and interactive UI designs. 💡 Key Highlights: Realistic rolling animations, optimized performance, and state management for user-friendly gameplay. Added a timer mechanism to prevent spamming and enhance interactivity. 🕒🎮',
        thumbnail: '/assets/thumbnails/3d-dice-roller.png', // Updated path to the thumbnail
        videoUrl: 'https://www.youtube.com/embed/-0uGWeEaMxw',
        views: '1.8K',
        likes: 198,
        date: '1 month ago',
        githubUrl: 'https://shadosxnover.github.io/3D-Dice-Roll/',
    },
    {
        id: '4',
        title: 'Shadoo Chat App',
        description: 'Shadoo Chat App is a real-time messaging application that makes communication seamless and engaging. It allows users to chat instantly with features like Google sign-in, personalized user profiles, and a clean, user-friendly interface. Built with React, Firebase Authentication, Firestore, and CSS, Shadoo Chat App combines simplicity and efficiency to deliver a dynamic chat experience for users. Perfect for anyone looking to explore real-time communication systems.',
        thumbnail: '/assets/thumbnails/shadoo-chat-app.png', // Updated path to the thumbnail
        videoUrl: 'https://www.youtube.com/embed/f5zc_e3s_Fg',
        views: '3.1K',
        likes: 256,
        date: '2 weeks ago',
        githubUrl: 'https://github.com/Shadosxnover/Chat-app',
    },
    {
        id: '5',
        title: 'Todo-app with Drag & Drop',
        description: 'To-do App is a powerful collaborative app that elevates the capabilities of real-time document editing. As an enhanced version of Google Docs, It supports millions of collaborators simultaneously, ensuring that every change is captured instantly and accurately.',
        thumbnail: '/assets/thumbnails/todo-app.png',
        videoUrl: 'https://www.youtube.com/embed/2mLLQayvNiM',
        views: '2K',
        likes: 198,
        date: '1 month ago',
        githubUrl: 'https://github.com/Shadosxnover/My-Todo-app',
    },
    {
        id: '6',
        title: 'Recipe Finder App',
        description: 'Recipe Finder App is a user-friendly app that allows users to search for recipes based on their preferences, ingredients, and dietary restrictions. It provides a convenient way to find delicious and healthy meals.',
        thumbnail: '/assets/thumbnails/recipe-finder.png',
        videoUrl: 'https://www.youtube.com/embed/OPRc1bLU0w4',
        views: '1.3K',
        likes: 98,
        date: '1 month ago',
        githubUrl: 'https://github.com/Shadosxnover/Recipe-app',
    },
];
